---
name: Build and Optionally Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Only
      uses: docker/bake-action@v2
      with:
        files: |
          ./docker-bake.hcl
    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to the Container registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Push
      if: steps['release']['outputs']['published'] == 'true'
      uses: docker/bake-action@v2
      env:
        TAG: ${{steps.release.outputs.release-version}}
      with:
        push: 'true'

  done:
    needs: [release]
    name: Done
    if: needs.release.release.result != 'success'
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
